### ISSUE TITLE
Execute on Save

### ISSUE THREAD

**Issue by red2678** [apptoix/bracketstoix#13]
Hi, how could I execute a bracketstoix command on Save?

**Comment by apptoix** [comment]
Hi. 
At this moment bracketstoIX can compile .js6 and .scss on save.
What did you need to execute on save? Depending on the situation, it could be possible.

Alexandre

**Comment by red2678** [comment]
Thanks for the quick response @apptoix.

IMO, it would be ideal if we could run any or all of the commands on save. A small UI like the keyboard shortcuts, but check boxes for executing the command on save. 

With regards to your response though, I would love the trim trailing white space, double quote to single, and space to tab if possible.

Thanks so much! Great extension, I I am setting up a 6 man FED department using brackets and your extension  :)

**Comment by apptoix** [comment]
Hi, 

At the time of the implementation of the trim trailing white spacing, I planned also to implement that command on save, but it ended up requiring more research time about Brackets API than I excepted.
With some extra research time, it shouldn't be hard to finish it.
As for the others requests, they sound useful as well, I will also have implemented on the next version, probably with with dual listbox tab on the option dialog the in order to support the command execution order.
I expect to launch the next version within 2 or 3 weeks. 

I'm glad you appreciate the extension, your feedback is welcome.

**Comment by apptoix** [comment]
Hi,
The new version is almost ready. 
This Monday it will be release with all the features that you requested.

**Comment by red2678** [comment]
:+1:  Wooo! Thanks!

**Comment by apptoix** [comment]
Hi,
I have just published the new version which includes the requested features.
Check out the video for its usage:
http://www.apptoix.com/en/bracketstoix.html#video

**Comment by red2678** [comment]
This is just great! TY so much :+1:
