### ISSUE TITLE
Sort Ascending for SASS

### ISSUE THREAD

**Issue by red2678** [apptoix/bracketstoix#15]
I would like to sort SASS rules ascending/descending. Currently I am working with a CSSComb extension. This is now the only feature that missing from bracketstoix. 

So how about it? Is this something that could implemented in bracketstoix?

Thanks!!

**Comment by apptoix** [comment]
At the moment there is no plans for implementing SASS rules sorting, although it wouldn't impossible in the future.
Future versions of bracketstoix, could execute external commands to process before on save, although at this moment I can't commit on a deadline.

At moment, there is a workaround that perhaps can solve what you need.
If the file has .scss extension (I don't known if that is the case), you can set on IX->Options->Compilers->SCSS a external script that would execute CSSComb followed by sass compiler.
I hope that solves.

To understand:
Before save/Compilers: Is executed when you do Save, Save All, Save As. It runs even for the documents that aren't active (Save All).

Before Save: Runs inside Brackets and you have to wait to finish to continue the edition, but it benefits from seeing the changes right away.

Compilers (After Save): It runs externally in parallel with Brackets, you don't have to wait for it's completion, but on the other hand if it modifies an opened file, you can only see the result after Brackets compares the internal file date with the stored file date. 

With time, I could re-evaluate this issue, since is planned a big improvement on the compilers part to provide more complex tasks.

**Comment by apptoix** [comment]
Hi.
On version 3.1 BracketstoIX allows to execute external scripts after save.
You can use this feature to sort SASS.
I hope this solve this issue.

Alexandre
