### ISSUE TITLE
Black Horizontal Patch

### ISSUE THREAD

**Issue by UniversalDesignz** [apptoix/bracketstoix#18]
Dear Sir,

I would like to inform you that the extension is loading up with a black horizontal patch, as you can see in the image I have attached with this message (I am using windows 10).

![black-patch](https://cloud.githubusercontent.com/assets/15095585/10438230/561f9a18-712a-11e5-9a0a-65c211418e06.png)

It would be nice to hear back from you with a solution.

I look forward for your responds.

Kindest Regards,
Jay

**Comment by apptoix** [comment]
Dear Jay,   
  
I'm also using Brackets+BracketstoIX on Windows 10, and I have no problems in displaying that dialog, as you can as see in the image that I'm attaching bellow.  

![bracketstoix-options-dialog](https://cloud.githubusercontent.com/assets/7297282/10444488/cd4aaf6e-7199-11e5-9e74-4ce467a2d907.png)

That situation is very awkward, since this version has been running stable for the last 5 months.
Could you provide me more details such as:
1. Did you had problems using with previous versions of Windows?
2. What is your Brackets version?
3. Does the other BracketstoIX dialog also has the same problem?
4. What is your graphic card?
5. Only this extension has this problem?

Sincerely,
Alexandre Bento Freire

**Comment by UniversalDesignz** [comment]
Dear Alexandre Bento Freire,

Thank you for your prompt response.

1.	Nope it worked fine.
2.	I am using the latest version that us Brackets 1.4+ Extract (Preview).
3.	Yep!I X TT and IX both does.
4.	AMD Radeon HD 8790M Graphics 2GB GDDR5.
5.	I have double checked, the problem seems to be just with !I X TT, IX  and one more plugin called Preference Func (Func Docr Setting).
6.	 Just for your attention Every-time I open up brackets a message at the top sows up saying - Starting installation.  (just doesn't like to go).

I look forward for your response.

Kindest Regards,
Jay.

**Comment by apptoix** [comment]
Dear Sir,

The message 'Starting installation' clearly shows there is something wrong with your installation.
My piece of advice is to uninstall Brackets, remove all the data associated with it, including plugins, and reinstall it again, otherwise you will have not only problem with two plugins, but other problems and plugins will also raise.
You might have another plugin causing this problem, my advice is after reinstalling Brackets, start by first adding BracketstoIX, and check it works well, and then keep adding the other plugins, so you can detect which is the offending plugin, though it might not be another plugin causing the problem.
You can also try to remove the other plugin which has the same problem, though I doubt that is the problem, since the situation is purely visually. 
In our company, we use BracketstoIX everyday including on Windows 10, and he have thousands of users running this version which has been stable for the last 5 months without problems on this area.

Another option is try a visual debug, by opening the BracketstoIX debugger, and try to change the CSS parameters of the visual fields that cause problems on BracketstoIX.
I'm attaching screenshots to illustrate how to do it, just in case you aren't aware of it.

![bracketstoix-f12](https://cloud.githubusercontent.com/assets/7297282/10472570/4aff394c-7254-11e5-95d7-6d7397581a42.png)
![bracketstoix-debug](https://cloud.githubusercontent.com/assets/7297282/10472572/59384dd2-7254-11e5-9c9b-4d0853ab3a0e.png)

If you have further inquires, don't hesitate to contact us again,

Sincerely,
Alexandre Bento Freire

**Comment by UniversalDesignz** [comment]
Good Morning Alexandre Bento Freire,

Last night I ended up uninstalling all the plugins as I thought might be a conflict. Guess what it's back to normal. Thank you for your support was very kind of you.

Have a fabulous day and keep smiling.

Kindest Regards,
Jay

**Comment by apptoix** [comment]
Hi Jay,

I'm glad all went all,
Have a great day!
Alexandre Bento Freire
